name: Update Submodule

on:
  repository_dispatch:
    types: [repo_b_updated]

jobs:
  build:
    name: update_submodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update submodule
        run: |
          git submodule update --remote

      # Step 4: Check for changes and push
      - name: Check for changes and push
        run: |
          git diff --exit-code || (git commit -am "Update submodule" && git push origin main) 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

